/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import controlador.Tipo;

/**
 *
 * @author elimo
 */
public class JFrameHistorial extends javax.swing.JFrame {


    /**
     * Creates new form JFrameHistorial
     */
    public JFrameHistorial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgHistorial = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnTramite = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnHistorialPlaca = new javax.swing.JButton();
        btnHistorialLicencia = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modulo historial.png"))); // NOI18N
        jPanel1.add(imgHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        btnAgregar.setText("jButton4");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 160, 90));

        btnTramite.setText("jButton1");
        btnTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramiteActionPerformed(evt);
            }
        });
        jPanel1.add(btnTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 160, 100));

        btnInicio.setText("jButton1");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 170, 100));

        btnHistorialPlaca.setText("jButton1");
        btnHistorialPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorialPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 190, 190));

        btnHistorialLicencia.setText("jButton1");
        btnHistorialLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialLicenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorialLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 190, 190));

        btnReporte.setText("jButton1");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        JFrameAgregar agregar = new JFrameAgregar();
        agregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramiteActionPerformed
        // TODO add your handling code here:
        JFrameTramitar tramite = new JFrameTramitar();
        tramite.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTramiteActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        JFrameInicio inicio = new JFrameInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnHistorialPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialPlacaActionPerformed
        // TODO add your handling code here:

        JFrameBuscar buscar = new JFrameBuscar(Tipo.PLACA);
        buscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialPlacaActionPerformed

    private void btnHistorialLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialLicenciaActionPerformed
        // TODO add your handling code here:

        JFrameBuscar buscar = new JFrameBuscar(Tipo.LICENCIA);
        buscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialLicenciaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnHistorialLicencia;
    private javax.swing.JButton btnHistorialPlaca;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnTramite;
    private javax.swing.JLabel imgHistorial;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
