/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import controlador.Tipo;

/**
 *
 * @author elimo
 */
public class JFrameBuscar extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBuscar
     * @param tipo
     */ 
    public JFrameBuscar(Tipo tipo) {
        initComponents();
        setLocationRelativeTo(null);
        if(tipo== Tipo.LICENCIA){
            tipoJLabel.setText("Estas buscando licencias");
        }else{
            tipoJLabel.setText("Estas buscando placas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        btnTramite = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnFechaNacimiento = new javax.swing.JButton();
        btnNombre = new javax.swing.JButton();
        btnCURP = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoJLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jPanel1.add(tipoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modulo historial (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 900, 500));

        btnHistorial.setText("jButton1");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 170, 90));

        btnTramite.setText("jButton1");
        btnTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramiteActionPerformed(evt);
            }
        });
        jPanel1.add(btnTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 170, 90));

        btnAgregar.setText("jButton1");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 160, 90));

        btnInicio.setText("jButton1");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 170, 90));

        btnFechaNacimiento.setText("jButton1");
        btnFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaNacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 180, 180));

        btnNombre.setText("jButton1");
        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });
        jPanel1.add(btnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 180, 180));

        btnCURP.setText("jButton1");
        btnCURP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCURPActionPerformed(evt);
            }
        });
        jPanel1.add(btnCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 180));

        btnAtras.setText("jButton1");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        JFrameHistorial historial = new JFrameHistorial();
        historial.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCURPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCURPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCURPActionPerformed

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFechaNacimientoActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        JFrameInicio inicio = new JFrameInicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        JFrameAgregar agregar = new JFrameAgregar();
        agregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramiteActionPerformed
        // TODO add your handling code here:
        JFrameTramitar tramite = new JFrameTramitar();
        tramite.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTramiteActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        JFrameHistorial historial = new JFrameHistorial();
        historial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCURP;
    private javax.swing.JButton btnFechaNacimiento;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNombre;
    private javax.swing.JButton btnTramite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tipoJLabel;
    // End of variables declaration//GEN-END:variables
}
